*&---------------------------------------------------------------------*
*&  Include           ZTR_APPR_REJ_SEL_SCN
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-001.
*SELECTION-SCREEN BEGIN OF LINE.
*SELECTION-SCREEN COMMENT 1(40) text-036.
*PARAMETER : p_dvclas TYPE DEVCLASS.
*SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(37) text-039.
*PARAMETER : p_trkorr TYPE trkorr OBLIGATORY.
select-OPTIONS: s_trkorr FOR e071-TRKORR NO INTERVALS OBLIGATORY.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(40) text-040.
PARAMETER : p_tarsys(40) TYPE C OBLIGATORY DEFAULT 'D22'.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(40) text-051.
PARAMETER : p_fpath(200) TYPE C.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(37) text-038.
SELECT-OPTIONS: s_mailid  FOR somlreci1-receiver NO INTERVALS.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b2.
